"""empty message

Revision ID: 7c89dafd9a2a
Revises: 0dca6b5f345c
Create Date: 2017-02-16 23:46:20.847426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c89dafd9a2a'
down_revision = '0dca6b5f345c'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(length=20), nullable=True),
    # sa.Column('password', sa.Text(), nullable=True),
    # sa.Column('avatar', sa.Text(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('username')
    # )
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('users')
    # ### end Alembic commands ###
