"""empty message

Revision ID: bde06cf6980d
Revises: 7c89dafd9a2a
Create Date: 2017-02-20 16:55:31.377296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde06cf6980d'
down_revision = '7c89dafd9a2a'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('drinks',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=140), nullable=True),
    # sa.Column('username', sa.String(), nullable=True),
    # sa.Column('ing1', sa.String(), nullable=True),
    # sa.Column('ing2', sa.String(), nullable=True),
    # sa.Column('ing3', sa.String(), nullable=True),
    # sa.Column('ing4', sa.String(), nullable=True),
    # sa.Column('ing5', sa.String(), nullable=True),
    # sa.Column('ing6', sa.String(), nullable=True),
    # sa.Column('garnish', sa.String(), nullable=True),
    # sa.Column('likes', sa.Integer(), nullable=True),
    # sa.Column('dislikes', sa.Integer(), nullable=True),
    # sa.Column('favorite', sa.Integer(), nullable=True),
    # sa.Column('user_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('drinks')
    # ### end Alembic commands ###
