"""empty message

Revision ID: e9301eac379c
Revises: 60c8899b4445
Create Date: 2017-02-23 10:52:53.827106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9301eac379c'
down_revision = '60c8899b4445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('ing1', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('ing2', sa.String(), nullable=True),
    sa.Column('ing3', sa.String(), nullable=True),
    sa.Column('ing4', sa.String(), nullable=True),
    sa.Column('ing5', sa.String(), nullable=True),
    sa.Column('ing6', sa.String(), nullable=True),
    sa.Column('garnish', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drinks')
    # ### end Alembic commands ###
